### PR TITLE
Updates to MooseVariableInterface and variable getter APIs

### LINKED ISSUE #286: Update MooseVariableInterface and other APIs for incorporation of vector finite elements
idaholab/moose#10238 is about ready to go and it has some API changes that will require some changes in apps.

### PR DESCRIPTION
**Pull request by lindsayad**
Need for incorporation of vector finite elements

Needs to wait for https://github.com/idaholab/moose/pull/10238

Closes #286

### CODE REVIEW

**Comment by dschwen** [comment]
Crap, I bet the thread test failures manifested after the change from TBB to pthreads.

**Comment by lindsayad** [comment]
So you're saying any PR would have failed here...

**Comment by lindsayad** [comment]
Yes, it looks like your threading has been [failing for a bit now](https://www.moosebuild.org/branch/425/), probably ever since the libmesh update:

magpie-failing-sad

**Comment by dschwen** [comment]
I'll merge this PR anyways. But I have some work cut out for me. This will be painful to debug....

**Pull request merged**
