### PR TITLE
Add DPAUserObject

### PR DESCRIPTION
**Pull request by snschune**
First step is to refactor `PolyatomicRecoil`.
Then I will inherit `DPAUserObject` from `ParkinCoulterBase`.

Refactoring the damage functions is delayed until I have this capability in.

### CODE REVIEW

**Comment by snschune** [comment]
@dschwen it's ready for an initial review. There is documentation and some more verification missing, though.

**Comment by dschwen** [comment]
Looks like there is a failure in parallel.

**Comment by snschune** [comment]
It's because information of the VPPs is not provided to `proc > 0`. 
Not sure why not.

**Comment by snschune** [comment]
@dschwen this is ready for your review.

**Pull request merged**
