### PR TITLE
Add missing include

### LINKED ISSUE #456: Add missing include
The complex types utility needs to include `DualOps.h` to make https://github.com/idaholab/moose/pull/16816 pass

### PR DESCRIPTION
**Pull request by dschwen**
Closes #456

(note there is an unrelated clang-format change)

### CODE REVIEW

**Comment by recuero** [comment]
Maybe you should revert the clang format change. I had to use the suggested CIVET patch to make it pass.

**Comment by dschwen** [comment]
Ugh, I was using an outdated clang-format version that ships with the atom plugin. Setting the plugin config to use `~/miniconda3/envs/moose/bin/clang-format` fixes it.

**Comment by dschwen** [comment]
The doc failure is due to a missing FFTW package on the new spack testing thingamajig. Pestering @loganharbour until its fixed :-D

**Review by recuero — APPROVED** [review]
Tests are passing.

**Pull request merged**
