### PR TITLE
Use external GSL installation

### PR DESCRIPTION
**Pull request by dschwen**
What do you think @snschune ? This will treat GSL the same way we treat FFTW. I have amended and tested the installation instructions for mac and Ubuntu. For this to pass @brianmoose will have to install the `libgsl-dev` package on the testboxes.

I think it really cleans (and speeds) up our build process. The only concern would be version incompatibilities (now that we do not precisely control the GSL version). But that would really surprise me with a library as mature as GSL.

### CODE REVIEW

**Comment by brianmoose** [comment]
I installed it on the build machines and invalidated. It still fails.
Note that the version on the build boxes is `2.1+dfsg-2` while your current submodule seems to be 2.4

**Comment by dschwen** [comment]
:-/ 2.1 is from 2015. Ok, let me investigate. So much for 

> that would really surprise me with a library as mature as GSL

**Comment by brianmoose** [comment]
Hmm,  it seems current magpie doesn't like it when there is a system libgsl: https://civet.inl.gov/job/222479/

**Comment by dschwen** [comment]
@brianmoose the compile error in App Tests should be fixed

**Comment by brianmoose** [comment]
Did you want to do the same `#ifdef GSL_ENABLED` for `src/userobjects/NeutronicsSprectrumSamplerSN.C`?

**Comment by dschwen** [comment]
Let me check. I built major with no gsl present and didn't get an error.
How did I miss this?

**Comment by dschwen** [comment]
Ah, because it has a
#ifdef RATTLESNAKE_ENABLED

**Pull request merged**
