### PR TITLE
Improved partial building of GSL 

### PR DESCRIPTION
**Pull request by dschwen**
Build only what's needed of GSL and link it in directly.

Refs #230

### CODE REVIEW

**Comment by dschwen** [comment]
This should also fix the _executable is really a shell script_ issue that makes debugging anoying.

**Comment by dschwen** [comment]
Crap. Works fine in clang.

**Comment by dschwen** [comment]
I'm starting to rethink this. We could include a small separate library for gauss-legendre quadrature and ditch GSL entirely. I found one that is internally used by GSL (http://www.holoborodko.com/pavel/numerical-methods/numerical-integration/)

**Comment by snschune** [comment]
Should this be closed then?

**Comment by dschwen** [comment]
Yes

**Pull request closed without merging**
