### PR TITLE
Avoid bug in older GCCs 

### LINKED ISSUE #357: Work around compiler bug in older GCC
Oder GCCs don't like the scope resolution operator in the contest below. Replacing this with `namespace` keywords should fix it. I'm working on replicating this on falcon (all my machines and VMs have gcc versions that are too new and do not have this bug).

Tagging @amanichen 

```
/home/a.cheniour/projects/magpie/build/header_symlinks/RadialGreensConvolution.h:172:26: error: specialization of ‘template<class T> class libMesh::Parallel::StandardType’ in different namespace [-fpermissive]
 class libMesh::Parallel::StandardType<RadialGreensConvolution::QPData> : public DataType
```

### PR DESCRIPTION
**Pull request by dschwen**
Closes #357

Ping @amanichen

### CODE REVIEW

**Comment by dschwen** [comment]
I should mention that I have indeed confirmed this fixes a compile error on Falcon with GCC 4.9.2

**Comment by brianmoose** [comment]
I  added the "minimum gcc" target which uses GCC 4.8.4

**Comment by dschwen** [comment]
Thanks @brianmoose !

**Comment by jessecarterMOOSE** [comment]
Thanks. This just bit me on GCC 6.2.0 (which isn't that old!)

**Pull request merged**
