### PR TITLE
Fix using define with PerfGraph changes

### LINKED ISSUE #465: Fix breakage from MOOSE PerfGraph changes
See https://civet.inl.gov/job/883096/.

`_perf_graph` member variable is no longer available.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #465

### CODE REVIEW

**Review by dschwen — APPROVED** [review]
is this using declaration even ... _used_?

**Comment by loganharbour** [comment]
Let's find out? I don't have fftw locally, so if you wanna check I wouldn't object

**Comment by dschwen** [comment]
```
mamba install fftw
```

is all that's needed!

**Comment by loganharbour** [comment]
Oh duh, silly me. Looks like it worked without.

**Pull request merged**
